# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "EAS503: Python for Data Scientists"
author: Mohammad Zia
copyright: "2024"
logo: ub.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# Information about where the book exists on the web
repository:
  url: https://github.com/mkzia/eas503-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  navbar_number_sections: true  
  home_page_in_navbar: false
  baseurl: "https://mkzia.github.io/eas503-notes"         